READING = {
    1: (
        "BAABB CCDAA CCACC DADCB DCBCA ADDDB DCABD CBAAC BDCCB ACDBC "
        "DCBCD CBDBC CDBBB ABCBB ADABC ADCDC DDACB BABAD DBBAA BADCA"
    ),
    2: (
        "CADBA DDCAA CDCDB CACDC ABACB DDCBA DBADA ADDBC DABDB BDCBC "
        "ABCCA BBCBB DBDDB ABCBD BCACB ACADB DBCDA CCADD ACDCB BACCD"
    ),
    3: (
        "BABCD BABAC BCBBD ADDAA BCDAB ACCCA ADABB BACBD CABCD CDCBD "
        "CDACA DCCDA BDBAC CACDC DADBD CBADB BCBAD ABCDC BDABB ABCDD"
    ),
    4: (
        "DBBCB ABABC BABAC DAABA CDDAC DCCAD CDDAC ADBAC DBBAC DADBD "
        "ADBDB BCBDC ABCCD CBABB DABDA CDDCA BADCB BABDC CBBAD ADCBA"
    ),
    5: (
        "CABBD ACAAC BCCBB DCCCA CDCDB BBBCD AACCD CBCCA ADACA BCCAD "
        "BDDAC DDCAB CDBDD BDACD BDACB CBCDB ACDBC ADCAB ADCCD BBDDC"
    ),
    6: (
        "CABBD ADABD CACDA DBCBD BBAAD DBCCD CADBD ACAAC BAACB ABDBD "
        "ABDDA ACABB CDDCB DADCC BBCDD BACDA DDCBC BCACB BDACB BDCAC"
    ),
    7: (
        "ABBAD DABAB ADCDB ACDCC DBAAB CDDAB CADBB ACBDB BCBDA CABAB "
        "BABAC DBBCA CCBBD CBCCC DABDD BDCCA CDCBA BCCDD CABDB ADCAD"
    ),
    8: (
        "BABAC BBCDA CBDBD BACCD ADCAC CDABB BADAC BDADB CBBAD ACBAD "
        "CBBCC ACCAB ABDDB CACDA DAADC DBACA BACCD DBCCB ABCBD DABCD"
    ),
    9: (
        "ABBCA ACABD CACBD ACBDD DBCCA BBBDA BDACD BABCD ADDCA ADADB "
        "CDBDA BBDCB ACDCB CDCAB CABCD DDABC CADCB BACDB CDCAB ACACB"
    ),
    10: (
        "ADBAD BABDB BABDC BCABA CDBDA ADDCB DCBAD BCBCA BDCDB DDBBD "
        "ADBCA CDCBD BDACD ABADB CCBAC BABCC BACDC ACDDB BBCDA BABCB"
    ),
}

def reading_key(test: int) -> dict[int, str]:
    letters = READING[test].replace(" ", "")
    if len(letters) != 100:
        raise ValueError(f"test {test}: expected 100 answers, got {len(letters)}")
    return {101 + i: c for i, c in enumerate(letters)}
