import type { SpeakLine } from '@/core/api/speaking.api'
import enLines from '@/data/english/speaking/lines.json'

/**
 * A speaking scenario. `opener` / `fallback` are optional: when a language ships
 * hand-written lines (Korean, English) they play offline; otherwise the opener
 * and replies are generated by the AI in the target language.
 *
 * In SpeakLine, `ko` always holds the target-language text (kept for back-compat)
 * and `vi` holds the translation into the learner's native language.
 */
export interface Scenario {
  id: string
  title: string
  emoji: string
  character: string
  role: string
  avatar: string
  situation: string
  persona: string
  /** Mục tiêu onboarding liên quan — tình huống hợp mục tiêu được xếp lên đầu. */
  tags?: string[]
  /** Cụm từ nên thuộc trước khi vào hội thoại — hiện trong bảng gấp được. */
  keyPhrases?: SpeakLine[]
  opener?: SpeakLine
  fallback?: { bot: SpeakLine[]; suggestions: SpeakLine[][] }
}

/**
 * Các tình huống mới chưa có lời thoại viết tay — AI đóng vai và mở lời
 * bằng ngôn ngữ đang học (mọi ngôn ngữ dùng chung, chỉ khác nhân vật).
 */
function extraScenarios(character: (name: string) => string): Scenario[] {
  return [
    {
      id: 'interview', title: 'Phỏng vấn xin việc', emoji: '💼',
      character: character('interview'), role: 'Người phỏng vấn', avatar: '🤝', tags: ['work'],
      situation: 'Bạn tham gia buổi phỏng vấn xin việc và trả lời các câu hỏi của nhà tuyển dụng.',
      persona: 'Bạn là người phỏng vấn thân thiện nhưng chuyên nghiệp. Hãy mời ứng viên giới thiệu bản thân, hỏi về kinh nghiệm, điểm mạnh, lý do ứng tuyển, rồi kết thúc tích cực.',
    },
    {
      id: 'hotel', title: 'Nhận phòng khách sạn', emoji: '🏨',
      character: character('hotel'), role: 'Lễ tân khách sạn', avatar: '🛎️', tags: ['travel'],
      situation: 'Bạn đến khách sạn đã đặt trước và làm thủ tục nhận phòng.',
      persona: 'Bạn là lễ tân khách sạn. Hãy xác nhận đặt phòng, xin hộ chiếu, giới thiệu giờ ăn sáng & wifi, rồi chúc khách nghỉ ngơi vui vẻ.',
    },
    {
      id: 'coworker', title: 'Trò chuyện với đồng nghiệp', emoji: '👔',
      character: character('coworker'), role: 'Đồng nghiệp cùng phòng', avatar: '💻', tags: ['work'],
      situation: 'Giờ nghỉ trưa, bạn trò chuyện thân mật với đồng nghiệp về công việc và cuối tuần.',
      persona: 'Bạn là đồng nghiệp vui tính. Hãy hỏi thăm dự án đang làm, than nhẹ về deadline, rủ ăn trưa và hỏi kế hoạch cuối tuần.',
    },
    {
      id: 'airport', title: 'Ở sân bay & taxi', emoji: '🛫',
      character: character('airport'), role: 'Nhân viên sân bay / tài xế', avatar: '🧳', tags: ['travel'],
      situation: 'Bạn làm thủ tục ở sân bay rồi bắt taxi về khách sạn.',
      persona: 'Bạn lần lượt đóng vai nhân viên check-in (hỏi hộ chiếu, hành lý, chỗ ngồi) rồi tài xế taxi (hỏi điểm đến, trò chuyện ngắn, báo giá).',
    },
    {
      id: 'meeting', title: 'Họp nhóm & báo cáo tiến độ', emoji: '📊',
      character: character('meeting'), role: 'Trưởng nhóm', avatar: '📊', tags: ['work'],
      situation: 'Cuộc họp đầu tuần: bạn báo cáo tiến độ công việc và nêu vướng mắc.',
      persona: 'Bạn là trưởng nhóm điều hành cuộc họp đầu tuần, nói ngắn gọn và chuyên nghiệp. Hãy hỏi tiến độ tuần qua, hỏi có gì đang cản trở, chốt trọng tâm tuần này rồi cảm ơn cả nhóm.',
    },
    {
      id: 'phonecall', title: 'Gọi điện công việc', emoji: '📞',
      character: character('phonecall'), role: 'Đối tác qua điện thoại', avatar: '📞', tags: ['work'],
      situation: 'Bạn gọi điện cho đối tác để xác nhận lịch hẹn — nghe không nhìn được khẩu hình nên khó hơn nói trực tiếp.',
      persona: 'Bạn nghe điện thoại công việc. Hãy chào theo kiểu điện thoại công sở, xác nhận người gọi là ai, có lúc xin nhắc lại vì đường dây không rõ, thống nhất lịch hẹn rồi chốt lại và chào tạm biệt.',
    },
    {
      id: 'presentation', title: 'Thuyết trình & hỏi đáp', emoji: '🎤',
      character: character('presentation'), role: 'Người nghe thuyết trình', avatar: '🎤', tags: ['work'],
      situation: 'Bạn trình bày ngắn về kế hoạch của mình rồi trả lời câu hỏi của người nghe.',
      persona: 'Bạn là khán giả trong buổi thuyết trình. Hãy mời người học bắt đầu, lắng nghe rồi đặt 2–3 câu hỏi làm rõ (con số, thời gian, chi phí), cuối cùng khen phần trình bày.',
    },
    {
      id: 'customer', title: 'Xử lý khiếu nại khách hàng', emoji: '🛟',
      character: character('customer'), role: 'Khách hàng đang bực', avatar: '🛟', tags: ['work'],
      situation: 'Một khách hàng phàn nàn vì đơn hàng giao muộn — bạn xin lỗi và đưa ra hướng xử lý.',
      persona: 'Bạn là khách hàng đang khó chịu vì đơn hàng giao muộn. Hãy nêu vấn đề, hỏi bao giờ nhận được, đòi giải pháp; khi người học xin lỗi và đưa hướng xử lý hợp lý thì nguôi giận và cảm ơn.',
    },
    {
      id: 'boss', title: 'Trao đổi với sếp', emoji: '🧑‍💼',
      character: character('boss'), role: 'Quản lý trực tiếp', avatar: '🧑‍💼', tags: ['work'],
      situation: 'Bạn gặp riêng quản lý để xin nghỉ phép hoặc xin thêm thời gian cho dự án.',
      persona: 'Bạn là quản lý trực tiếp, nghiêm túc nhưng thấu hiểu. Hãy hỏi người học cần gì, hỏi lý do và ảnh hưởng tới tiến độ, đề nghị phương án rồi chốt lại.',
    },
    {
      id: 'networking', title: 'Làm quen ở sự kiện nghề nghiệp', emoji: '🥂',
      character: character('networking'), role: 'Người dự hội thảo', avatar: '🥂', tags: ['work', 'talk'],
      situation: 'Giờ giải lao một hội thảo, bạn bắt chuyện với người tham dự khác.',
      persona: 'Bạn là một người dự hội thảo cởi mở. Hãy bắt chuyện tự nhiên, hỏi họ làm nghề gì và ở công ty nào, hỏi cảm nhận về hội thảo, rồi đề nghị giữ liên lạc.',
    },
    {
      id: 'bank', title: 'Ngân hàng & giấy tờ', emoji: '🏦',
      character: character('bank'), role: 'Giao dịch viên ngân hàng', avatar: '🏦', tags: ['talk', 'travel'],
      situation: 'Bạn đến ngân hàng để mở tài khoản hoặc đổi tiền.',
      persona: 'Bạn là giao dịch viên ngân hàng. Hãy hỏi khách cần gì, yêu cầu giấy tờ tuỳ thân, giải thích phí và thời gian chờ, rồi hướng dẫn khách ký giấy tờ.',
    },
    {
      id: 'rent', title: 'Thuê nhà & gọi thợ sửa', emoji: '🔧',
      character: character('rent'), role: 'Chủ nhà', avatar: '🏠', tags: ['talk'],
      situation: 'Đồ trong phòng trọ bị hỏng, bạn gọi chủ nhà để báo và hẹn thợ đến sửa.',
      persona: 'Bạn là chủ nhà thân thiện. Hãy hỏi hỏng cái gì, hỏng từ khi nào, xin lỗi vì bất tiện, hẹn ngày giờ thợ tới rồi xác nhận lại.',
    },
    {
      id: 'pharmacy', title: 'Ở hiệu thuốc', emoji: '💊',
      character: character('pharmacy'), role: 'Dược sĩ', avatar: '💊', tags: ['travel', 'talk'],
      situation: 'Bạn bị ốm khi đang ở nước ngoài và vào hiệu thuốc mua thuốc.',
      persona: 'Bạn là dược sĩ. Hãy hỏi triệu chứng, hỏi có sốt không, hỏi có dị ứng thuốc nào không, giới thiệu thuốc phù hợp kèm liều dùng rồi chúc mau khỏe.',
    },
    {
      id: 'emergency', title: 'Tình huống khẩn cấp', emoji: '🚨',
      character: character('emergency'), role: 'Tổng đài khẩn cấp', avatar: '🚨', tags: ['travel', 'talk'],
      situation: 'Bạn gặp sự cố khi ở nước ngoài và gọi tổng đài khẩn cấp nhờ trợ giúp.',
      persona: 'Bạn là nhân viên tổng đài khẩn cấp, bình tĩnh và rõ ràng. Hãy hỏi chuyện gì xảy ra, hỏi vị trí chính xác, hỏi có ai bị thương không, trấn an và báo đã cử người tới.',
    },
  ]
}

const KO_SCENARIOS: Scenario[] = [
  {
    id: 'greet', title: 'Chào hỏi & làm quen', emoji: '👋',
    character: '지우', role: 'Người bạn Hàn Quốc', avatar: '🧑', tags: ['talk'],
    situation: 'Bạn gặp một người bạn Hàn Quốc lần đầu và làm quen.',
    persona: 'Bạn là 지우, một người Hàn Quốc trẻ, thân thiện, đang làm quen với người học. Hãy hỏi tên, quê quán, lý do học tiếng Hàn rồi động viên họ.',
    opener: { ko: '안녕하세요! 만나서 반갑습니다. 이름이 뭐예요?', vi: 'Xin chào! Rất vui được gặp. Bạn tên gì?' },
    fallback: {
      bot: [
        { ko: '와, 좋은 이름이네요! 어디에서 왔어요?', vi: 'Ồ, tên hay đấy! Bạn đến từ đâu?' },
        { ko: '베트남이군요! 한국어를 왜 배워요?', vi: 'Việt Nam à! Bạn học tiếng Hàn vì sao?' },
        { ko: '멋져요! 매일 조금씩 연습하면 금방 늘어요. 화이팅!', vi: 'Tuyệt vời! Mỗi ngày luyện một chút là tiến bộ nhanh thôi. Cố lên!' },
      ],
      suggestions: [
        [{ ko: '제 이름은 민수예요.', vi: 'Tên tôi là Minsu.' }, { ko: '저는 흐엉이에요.', vi: 'Tôi là Hương.' }],
        [{ ko: '베트남에서 왔어요.', vi: 'Tôi đến từ Việt Nam.' }],
        [{ ko: 'K-pop을 좋아해서 배워요.', vi: 'Tôi học vì thích K-pop.' }, { ko: '한국 여행을 가고 싶어요.', vi: 'Tôi muốn đi du lịch Hàn Quốc.' }],
        [{ ko: '감사합니다! 열심히 할게요.', vi: 'Cảm ơn! Tôi sẽ cố gắng.' }],
      ],
    },
  },
  {
    id: 'clinic', title: 'Đặt lịch khám bệnh', emoji: '🏥',
    character: '지우', role: 'Lễ tân phòng khám 햇살 내과', avatar: '🩺', tags: ['talk'],
    situation: 'Bạn gọi điện đến phòng khám nội khoa để đặt lịch khám.',
    persona: 'Bạn là 지우, lễ tân phòng khám nội khoa 햇살 내과. Hãy hỏi triệu chứng, sắp xếp giờ hẹn, rồi xin tên và số điện thoại của bệnh nhân.',
    opener: { ko: '안녕하세요. 햇살 내과입니다. 오늘 진료 예약 때문에 전화하셨나요?', vi: 'Xin chào. Đây là phòng khám nội khoa Haetsal. Bạn gọi điện để đặt lịch khám hôm nay phải không?' },
    fallback: {
      bot: [
        { ko: '네, 어디가 불편하세요?', vi: 'Vâng, bạn thấy không khỏe ở đâu ạ?' },
        { ko: '알겠습니다. 오후 3시 괜찮으세요?', vi: 'Tôi hiểu rồi. 3 giờ chiều có được không ạ?' },
        { ko: '네, 예약되었습니다. 성함과 연락처를 알려 주세요.', vi: 'Vâng, đã đặt lịch. Cho tôi biết tên và số điện thoại nhé.' },
      ],
      suggestions: [
        [
          { ko: '네, 오늘 진료를 받고 싶어요.', vi: 'Vâng, tôi muốn được khám bệnh hôm nay.' },
          { ko: '네, 예약이 가능한지 물어보려고요.', vi: 'Vâng, tôi muốn hỏi xem có đặt lịch được không.' },
          { ko: '감기 기운이 있어서 예약하고 싶어요.', vi: 'Tôi có dấu hiệu bị cảm nên muốn đặt lịch.' },
        ],
        [{ ko: '감기에 걸린 것 같아요.', vi: 'Hình như tôi bị cảm.' }, { ko: '목이 아프고 열이 나요.', vi: 'Tôi đau họng và bị sốt.' }],
        [{ ko: '네, 괜찮아요.', vi: 'Vâng, được ạ.' }, { ko: '혹시 더 이른 시간 있어요?', vi: 'Có giờ nào sớm hơn không ạ?' }],
        [{ ko: '제 이름은 흐엉이에요. 번호는 010-1234-5678이에요.', vi: 'Tên tôi là Hương. Số là 010-1234-5678.' }],
      ],
    },
  },
  {
    id: 'cafe', title: 'Gọi món ở quán cà phê', emoji: '☕',
    character: '민준', role: 'Nhân viên quán cà phê', avatar: '☕', tags: ['talk', 'travel'],
    situation: 'Bạn vào quán cà phê và gọi đồ uống.',
    persona: 'Bạn là 민준, nhân viên một quán cà phê. Hãy nhận order, hỏi nóng/lạnh, hỏi cỡ ly rồi báo khách đợi.',
    opener: { ko: '어서 오세요! 무엇을 드릴까요?', vi: 'Mời vào! Bạn muốn dùng gì ạ?' },
    fallback: {
      bot: [
        { ko: '따뜻한 거요, 차가운 거요?', vi: 'Bạn muốn nóng hay lạnh ạ?' },
        { ko: '사이즈는 어떻게 하시겠어요?', vi: 'Bạn muốn cỡ nào ạ?' },
        { ko: '네, 잠시만 기다려 주세요. 감사합니다!', vi: 'Vâng, xin đợi một chút. Cảm ơn ạ!' },
      ],
      suggestions: [
        [{ ko: '아메리카노 한 잔 주세요.', vi: 'Cho tôi một ly americano.' }, { ko: '카페라떼 주세요.', vi: 'Cho tôi cà phê latte.' }],
        [{ ko: '차가운 걸로 주세요.', vi: 'Cho tôi loại lạnh.' }, { ko: '따뜻한 걸로요.', vi: 'Loại nóng ạ.' }],
        [{ ko: '큰 사이즈로 주세요.', vi: 'Cho tôi cỡ lớn.' }],
        [{ ko: '감사합니다!', vi: 'Cảm ơn ạ!' }],
      ],
    },
  },
  {
    id: 'restaurant', title: 'Ăn ở nhà hàng', emoji: '🍜',
    character: '서연', role: 'Nhân viên nhà hàng', avatar: '🍽️', tags: ['talk', 'travel'],
    situation: 'Bạn vào một nhà hàng Hàn Quốc và gọi món ăn.',
    persona: 'Bạn là 서연, nhân viên nhà hàng Hàn Quốc. Hãy hỏi số người, mời thực đơn, nhận order rồi chúc khách ngon miệng.',
    opener: { ko: '어서 오세요! 몇 분이세요?', vi: 'Mời vào! Quý khách mấy người ạ?' },
    fallback: {
      bot: [
        { ko: '네, 이쪽으로 오세요. 메뉴 여기 있습니다.', vi: 'Vâng, mời đi lối này. Thực đơn đây ạ.' },
        { ko: '주문하시겠어요?', vi: 'Quý khách gọi món chưa ạ?' },
        { ko: '네, 잠시만 기다려 주세요. 맛있게 드세요!', vi: 'Vâng, xin đợi chút. Chúc ngon miệng!' },
      ],
      suggestions: [
        [{ ko: '두 명이요.', vi: 'Hai người ạ.' }, { ko: '혼자예요.', vi: 'Một mình ạ.' }],
        [{ ko: '네, 추천 메뉴가 뭐예요?', vi: 'Vâng, món nào ngon ạ?' }],
        [{ ko: '비빔밥 하나 주세요.', vi: 'Cho tôi một phần bibimbap.' }, { ko: '김치찌개 주세요.', vi: 'Cho tôi canh kimchi.' }],
        [{ ko: '감사합니다!', vi: 'Cảm ơn ạ!' }],
      ],
    },
  },
  {
    id: 'shopping', title: 'Mua sắm', emoji: '🛍️',
    character: '하준', role: 'Nhân viên cửa hàng', avatar: '🛍️', tags: ['travel', 'talk'],
    situation: 'Bạn vào cửa hàng quần áo và muốn mua đồ.',
    persona: 'Bạn là 하준, nhân viên cửa hàng quần áo. Hãy giới thiệu sản phẩm, hỏi cỡ, mời khách thử đồ và báo giá.',
    opener: { ko: '어서 오세요! 무엇을 찾으세요?', vi: 'Mời vào! Bạn tìm gì ạ?' },
    fallback: {
      bot: [
        { ko: '이 옷은 어떠세요? 요즘 인기가 많아요.', vi: 'Cái áo này thế nào? Dạo này được ưa chuộng lắm.' },
        { ko: '사이즈가 어떻게 되세요?', vi: 'Bạn mặc cỡ bao nhiêu ạ?' },
        { ko: '네, 여기 있습니다. 입어 보시겠어요?', vi: 'Vâng, đây ạ. Bạn thử nhé?' },
      ],
      suggestions: [
        [{ ko: '티셔츠를 보고 있어요.', vi: 'Tôi đang xem áo phông.' }, { ko: '그냥 구경하고 있어요.', vi: 'Tôi chỉ xem thôi ạ.' }],
        [{ ko: '예뻐요! 얼마예요?', vi: 'Đẹp đấy! Bao nhiêu tiền ạ?' }],
        [{ ko: '미디엄이요.', vi: 'Cỡ M ạ.' }, { ko: '라지 있어요?', vi: 'Có cỡ L không ạ?' }],
        [{ ko: '네, 입어 볼게요.', vi: 'Vâng, tôi thử ạ.' }],
      ],
    },
  },
  {
    id: 'direction', title: 'Hỏi đường', emoji: '🧭',
    character: '행인', role: 'Người qua đường', avatar: '🧭', tags: ['travel'],
    situation: 'Bạn bị lạc và hỏi đường một người qua đường.',
    persona: 'Bạn là một người qua đường tốt bụng ở Hàn Quốc. Hãy chỉ đường, cho biết khoảng cách/thời gian rồi chào tạm biệt thân thiện.',
    opener: { ko: '저기요, 무엇을 찾으세요?', vi: 'Xin lỗi, bạn đang tìm gì vậy?' },
    fallback: {
      bot: [
        { ko: '아, 지하철역이요? 이 길로 쭉 가세요.', vi: 'À, ga tàu điện ngầm à? Bạn cứ đi thẳng đường này.' },
        { ko: '걸어서 5분 정도 걸려요.', vi: 'Đi bộ khoảng 5 phút.' },
        { ko: '천만에요! 조심히 가세요.', vi: 'Không có gì! Đi cẩn thận nhé.' },
      ],
      suggestions: [
        [{ ko: '지하철역이 어디예요?', vi: 'Ga tàu điện ngầm ở đâu ạ?' }, { ko: '화장실이 어디예요?', vi: 'Nhà vệ sinh ở đâu ạ?' }],
        [{ ko: '얼마나 걸려요?', vi: 'Mất bao lâu ạ?' }],
        [{ ko: '감사합니다!', vi: 'Cảm ơn ạ!' }],
      ],
    },
  },
]

const EN_SCENARIOS: Scenario[] = [
  {
    id: 'greet', title: 'Chào hỏi & làm quen', emoji: '👋',
    character: 'Emma', role: 'Người bạn nói tiếng Anh', avatar: '🧑', tags: ['talk'],
    situation: 'Bạn gặp một người bạn nói tiếng Anh lần đầu và làm quen.',
    persona: 'Bạn là Emma, một người trẻ thân thiện đang làm quen với người học. Hãy hỏi tên, quê quán, lý do học tiếng Anh rồi động viên họ.',
    opener: { ko: "Hi! Nice to meet you. What's your name?", vi: 'Chào! Rất vui được gặp bạn. Bạn tên gì?' },
    fallback: {
      bot: [
        { ko: 'Oh, nice name! Where are you from?', vi: 'Ồ, tên hay đấy! Bạn đến từ đâu?' },
        { ko: 'Vietnam, cool! Why are you learning English?', vi: 'Việt Nam, tuyệt! Vì sao bạn học tiếng Anh?' },
        { ko: "That's great! Practice a little every day and you'll improve fast. Good luck!", vi: 'Tuyệt vời! Mỗi ngày luyện một chút là tiến bộ nhanh thôi. Cố lên!' },
      ],
      suggestions: [
        [{ ko: 'My name is Minsu.', vi: 'Tên tôi là Minsu.' }, { ko: "I'm Huong.", vi: 'Tôi là Hương.' }],
        [{ ko: "I'm from Vietnam.", vi: 'Tôi đến từ Việt Nam.' }],
        [{ ko: 'I learn it for work.', vi: 'Tôi học vì công việc.' }, { ko: 'I want to travel abroad.', vi: 'Tôi muốn đi du lịch nước ngoài.' }],
        [{ ko: "Thank you! I'll do my best.", vi: 'Cảm ơn! Tôi sẽ cố gắng.' }],
      ],
    },
  },
  {
    id: 'cafe', title: 'Gọi món ở quán cà phê', emoji: '☕',
    character: 'Jack', role: 'Nhân viên quán cà phê', avatar: '☕', tags: ['talk', 'travel'],
    situation: 'Bạn vào quán cà phê và gọi đồ uống.',
    persona: 'Bạn là Jack, nhân viên một quán cà phê. Hãy nhận order, hỏi nóng/đá, hỏi cỡ ly rồi báo khách đợi.',
    opener: { ko: 'Hi there! What can I get for you?', vi: 'Chào bạn! Bạn muốn dùng gì ạ?' },
    fallback: {
      bot: [
        { ko: 'Hot or iced?', vi: 'Nóng hay đá ạ?' },
        { ko: 'What size would you like?', vi: 'Bạn muốn cỡ nào ạ?' },
        { ko: 'Sure, one moment please. Thank you!', vi: 'Vâng, xin đợi một chút. Cảm ơn ạ!' },
      ],
      suggestions: [
        [{ ko: 'A cup of coffee, please.', vi: 'Cho tôi một ly cà phê.' }, { ko: 'Can I get a latte?', vi: 'Cho tôi một ly latte nhé?' }],
        [{ ko: 'Iced, please.', vi: 'Cho đá ạ.' }, { ko: 'Hot, please.', vi: 'Nóng ạ.' }],
        [{ ko: 'Large, please.', vi: 'Cỡ lớn ạ.' }],
        [{ ko: 'Thank you!', vi: 'Cảm ơn ạ!' }],
      ],
    },
  },
  {
    id: 'restaurant', title: 'Ăn ở nhà hàng', emoji: '🍽️',
    character: 'Olivia', role: 'Nhân viên nhà hàng', avatar: '🍽️', tags: ['talk', 'travel'],
    situation: 'Bạn vào một nhà hàng và gọi món ăn.',
    persona: 'Bạn là Olivia, nhân viên nhà hàng. Hãy hỏi số người, mời thực đơn, nhận order rồi chúc khách ngon miệng.',
    opener: { ko: 'Welcome! How many people?', vi: 'Mời vào! Quý khách mấy người ạ?' },
    fallback: {
      bot: [
        { ko: "This way, please. Here's the menu.", vi: 'Mời đi lối này ạ. Thực đơn đây ạ.' },
        { ko: 'Are you ready to order?', vi: 'Quý khách gọi món chưa ạ?' },
        { ko: "Great, it'll be ready soon. Enjoy your meal!", vi: 'Tuyệt, món sẽ ra ngay. Chúc ngon miệng!' },
      ],
      suggestions: [
        [{ ko: 'Two people.', vi: 'Hai người ạ.' }, { ko: 'Just me.', vi: 'Một mình ạ.' }],
        [{ ko: 'What do you recommend?', vi: 'Bạn gợi ý món nào ạ?' }],
        [{ ko: "I'll have the chicken.", vi: 'Cho tôi món gà.' }, { ko: 'A burger, please.', vi: 'Cho tôi một burger.' }],
        [{ ko: 'Thank you!', vi: 'Cảm ơn ạ!' }],
      ],
    },
  },
  {
    id: 'shopping', title: 'Mua sắm', emoji: '🛍️',
    character: 'Liam', role: 'Nhân viên cửa hàng', avatar: '🛍️', tags: ['travel', 'talk'],
    situation: 'Bạn vào cửa hàng quần áo và muốn mua đồ.',
    persona: 'Bạn là Liam, nhân viên cửa hàng quần áo. Hãy giới thiệu sản phẩm, hỏi cỡ, mời khách thử đồ và báo giá.',
    opener: { ko: 'Hi! Are you looking for anything in particular?', vi: 'Chào bạn! Bạn đang tìm gì ạ?' },
    fallback: {
      bot: [
        { ko: 'How about this one? It is very popular.', vi: 'Cái này thì sao? Đang được ưa chuộng lắm.' },
        { ko: 'What size are you?', vi: 'Bạn mặc cỡ nào ạ?' },
        { ko: 'Here you go. Would you like to try it on?', vi: 'Của bạn đây. Bạn thử nhé?' },
      ],
      suggestions: [
        [{ ko: "I'm looking for a T-shirt.", vi: 'Tôi đang tìm áo phông.' }, { ko: "I'm just looking, thanks.", vi: 'Tôi chỉ xem thôi, cảm ơn.' }],
        [{ ko: 'Nice! How much is it?', vi: 'Đẹp đấy! Bao nhiêu tiền ạ?' }],
        [{ ko: 'Medium, please.', vi: 'Cỡ M ạ.' }, { ko: 'Do you have a large?', vi: 'Có cỡ L không ạ?' }],
        [{ ko: "Yes, I'll try it on.", vi: 'Vâng, tôi thử ạ.' }],
      ],
    },
  },
  {
    id: 'direction', title: 'Hỏi đường', emoji: '🧭',
    character: 'Passerby', role: 'Người qua đường', avatar: '🧭', tags: ['travel'],
    situation: 'Bạn bị lạc và hỏi đường một người qua đường.',
    persona: 'Bạn là một người qua đường tốt bụng. Hãy chỉ đường, cho biết khoảng cách/thời gian rồi chào tạm biệt thân thiện.',
    opener: { ko: 'Excuse me, are you looking for something?', vi: 'Xin lỗi, bạn đang tìm gì vậy?' },
    fallback: {
      bot: [
        { ko: 'The station? Go straight down this street.', vi: 'Nhà ga à? Bạn cứ đi thẳng đường này.' },
        { ko: "It's about a five-minute walk.", vi: 'Đi bộ khoảng 5 phút.' },
        { ko: "You're welcome! Take care.", vi: 'Không có gì! Đi cẩn thận nhé.' },
      ],
      suggestions: [
        [{ ko: 'Where is the station?', vi: 'Nhà ga ở đâu ạ?' }, { ko: "Where's the restroom?", vi: 'Nhà vệ sinh ở đâu ạ?' }],
        [{ ko: 'How long does it take?', vi: 'Mất bao lâu ạ?' }],
        [{ ko: 'Thank you!', vi: 'Cảm ơn ạ!' }],
      ],
    },
  },
  {
    id: 'clinic', title: 'Đặt lịch khám bệnh', emoji: '🏥',
    character: 'Sophia', role: 'Lễ tân phòng khám Sunshine', avatar: '🩺', tags: ['talk'],
    situation: 'Bạn gọi điện đến phòng khám để đặt lịch khám.',
    persona: 'Bạn là Sophia, lễ tân phòng khám Sunshine. Hãy hỏi triệu chứng, sắp xếp giờ hẹn rồi xin tên và số điện thoại của bệnh nhân.',
    opener: { ko: 'Hello, Sunshine Clinic. Are you calling to book an appointment?', vi: 'Xin chào, phòng khám Sunshine. Bạn gọi để đặt lịch khám ạ?' },
    fallback: {
      bot: [
        { ko: 'Sure. What seems to be the problem?', vi: 'Vâng. Bạn thấy không khỏe ở đâu ạ?' },
        { ko: 'Okay. Does 3 p.m. work for you?', vi: 'Được ạ. 3 giờ chiều có tiện không ạ?' },
        { ko: 'Great, you are booked. May I have your name and number?', vi: 'Tuyệt, đã đặt lịch. Cho tôi xin tên và số điện thoại nhé.' },
      ],
      suggestions: [
        [{ ko: "Yes, I'd like to see a doctor today.", vi: 'Vâng, hôm nay tôi muốn được khám.' }, { ko: 'Yes, can I make an appointment?', vi: 'Vâng, tôi đặt lịch được không ạ?' }],
        [{ ko: 'I think I have a cold.', vi: 'Hình như tôi bị cảm.' }, { ko: 'I have a sore throat and a fever.', vi: 'Tôi đau họng và sốt.' }],
        [{ ko: 'Yes, that works.', vi: 'Vâng, được ạ.' }, { ko: 'Is there anything earlier?', vi: 'Có giờ nào sớm hơn không ạ?' }],
        [{ ko: "I'm Huong, 0123 456 789.", vi: 'Tôi là Hương, 0123 456 789.' }],
      ],
    },
  },
]

// Meta-only templates for languages without hand-written lines — the AI plays the
// character and opens the conversation in the target language.
const GENERIC_SCENARIOS: Scenario[] = [
  {
    id: 'greet', title: 'Chào hỏi & làm quen', emoji: '👋',
    character: 'Alex', role: 'Người bạn bản xứ', avatar: '🧑', tags: ['talk'],
    situation: 'Bạn gặp một người bạn bản xứ lần đầu và làm quen.',
    persona: 'Bạn là một người bản xứ trẻ, thân thiện đang làm quen với người học. Hãy hỏi tên, quê quán, lý do học ngoại ngữ rồi động viên họ.',
  },
  {
    id: 'cafe', title: 'Gọi món ở quán cà phê', emoji: '☕',
    character: 'Sam', role: 'Nhân viên quán cà phê', avatar: '☕', tags: ['talk', 'travel'],
    situation: 'Bạn vào quán cà phê và gọi đồ uống.',
    persona: 'Bạn là nhân viên một quán cà phê. Hãy nhận order, hỏi nóng/đá, hỏi cỡ ly rồi báo khách đợi.',
  },
  {
    id: 'restaurant', title: 'Ăn ở nhà hàng', emoji: '🍽️',
    character: 'Mia', role: 'Nhân viên nhà hàng', avatar: '🍽️', tags: ['talk', 'travel'],
    situation: 'Bạn vào một nhà hàng và gọi món ăn.',
    persona: 'Bạn là nhân viên nhà hàng. Hãy hỏi số người, mời thực đơn, nhận order rồi chúc khách ngon miệng.',
  },
  {
    id: 'shopping', title: 'Mua sắm', emoji: '🛍️',
    character: 'Leo', role: 'Nhân viên cửa hàng', avatar: '🛍️', tags: ['travel', 'talk'],
    situation: 'Bạn vào cửa hàng quần áo và muốn mua đồ.',
    persona: 'Bạn là nhân viên cửa hàng quần áo. Hãy giới thiệu sản phẩm, hỏi cỡ, mời khách thử đồ và báo giá.',
  },
  {
    id: 'direction', title: 'Hỏi đường', emoji: '🧭',
    character: 'Jamie', role: 'Người qua đường', avatar: '🧭', tags: ['travel'],
    situation: 'Bạn bị lạc và hỏi đường một người qua đường.',
    persona: 'Bạn là một người qua đường tốt bụng. Hãy chỉ đường, cho biết khoảng cách/thời gian rồi chào tạm biệt thân thiện.',
  },
  {
    id: 'clinic', title: 'Đặt lịch khám bệnh', emoji: '🏥',
    character: 'Robin', role: 'Lễ tân phòng khám', avatar: '🩺', tags: ['talk'],
    situation: 'Bạn gọi điện đến phòng khám để đặt lịch khám.',
    persona: 'Bạn là lễ tân phòng khám. Hãy hỏi triệu chứng, sắp xếp giờ hẹn rồi xin tên và số điện thoại của bệnh nhân.',
  },
]

const KO_EXTRA_NAMES: Record<string, string> = {
  interview: '김 부장', hotel: '수민', coworker: '민재', airport: '하늘',
  meeting: '박 팀장', phonecall: '정 대리', presentation: '강 과장', customer: '최 손님', boss: '한 부장',
  networking: '윤서', bank: '은행 직원', rent: '집주인 아주머니', pharmacy: '약사 선생님', emergency: '119 상황실',
}
const EN_EXTRA_NAMES: Record<string, string> = {
  interview: 'Mr. Carter', hotel: 'Grace', coworker: 'Tom', airport: 'Ryan',
  meeting: 'Sarah', phonecall: 'Daniel', presentation: 'Peter', customer: 'Mr. Hall', boss: 'Ms. Reed',
  networking: 'Chris', bank: 'Anna', rent: 'Mrs. Brown', pharmacy: 'David', emergency: 'Operator',
}
const GENERIC_EXTRA_NAMES: Record<string, string> = {
  interview: 'Morgan', hotel: 'Noa', coworker: 'Kim', airport: 'Ari',
  meeting: 'Robin', phonecall: 'Jordan', presentation: 'Casey', customer: 'Riley', boss: 'Taylor',
  networking: 'Avery', bank: 'Quinn', rent: 'Rowan', pharmacy: 'Sky', emergency: 'Operator',
}

// Lời thoại viết tay tiếng Anh: gắn vào tình huống theo id để phần Luyện nói EN
// vẫn chạy trọn vẹn khi AI lỗi hoặc hết hạn mức.
type EnLines = { keyPhrases?: SpeakLine[]; opener?: SpeakLine; bot?: SpeakLine[]; suggestions?: SpeakLine[][] }
const EN_LINES = enLines as Record<string, EnLines>

function withEnLines(list: Scenario[]): Scenario[] {
  return list.map((s) => {
    const l = EN_LINES[s.id]
    if (!l) return s
    return {
      ...s,
      keyPhrases: s.keyPhrases ?? l.keyPhrases,
      opener: s.opener ?? l.opener,
      fallback: s.fallback ?? (l.bot && l.suggestions ? { bot: l.bot, suggestions: l.suggestions } : undefined),
    }
  })
}

const BY_LANG: Record<string, Scenario[]> = {
  ko: [...KO_SCENARIOS, ...extraScenarios((id) => KO_EXTRA_NAMES[id] || '지우')],
  en: withEnLines([...EN_SCENARIOS, ...extraScenarios((id) => EN_EXTRA_NAMES[id] || 'Alex')]),
}

const GENERIC_ALL = [...GENERIC_SCENARIOS, ...extraScenarios((id) => GENERIC_EXTRA_NAMES[id] || 'Alex')]

export function scenariosFor(lang: string): Scenario[] {
  return BY_LANG[lang] || GENERIC_ALL
}

/* ------------------- Hội thoại ngẫu nhiên — mỗi lần một đề tài ------------------- */

const RANDOM_TOPICS: { emoji: string; topic: string; hint: string }[] = [
  { emoji: '🌦️', topic: 'thời tiết hôm nay', hint: 'Hỏi cảm nhận về thời tiết, gợi ý hoạt động phù hợp với trời hôm nay.' },
  { emoji: '🍜', topic: 'món ăn yêu thích', hint: 'Hỏi món ăn người học thích nhất, tả món bạn thích, rủ đi ăn thử.' },
  { emoji: '🎬', topic: 'phim & series đang xem', hint: 'Hỏi phim gần đây họ xem, kể một phim bạn mê, tranh luận nhẹ nhàng thể loại hay nhất.' },
  { emoji: '🎵', topic: 'âm nhạc & ca sĩ yêu thích', hint: 'Hỏi gu nhạc, ca sĩ yêu thích, concert trong mơ.' },
  { emoji: '✈️', topic: 'nơi muốn du lịch nhất', hint: 'Hỏi nơi họ mơ ước đến, kể nơi bạn từng đi, lên kế hoạch chuyến đi tưởng tượng.' },
  { emoji: '📅', topic: 'kế hoạch cuối tuần', hint: 'Hỏi cuối tuần này làm gì, gợi ý hoạt động thú vị, hẹn gặp thử.' },
  { emoji: '🐶', topic: 'thú cưng', hint: 'Hỏi họ có nuôi thú cưng không, kể về thú cưng của bạn, tranh luận vui chó hay mèo.' },
  { emoji: '💪', topic: 'thể thao & vận động', hint: 'Hỏi môn thể thao họ chơi/xem, thói quen tập luyện, rủ tập cùng.' },
  { emoji: '📚', topic: 'sách & thói quen đọc', hint: 'Hỏi cuốn sách gần đây, thể loại yêu thích, xin gợi ý một cuốn.' },
  { emoji: '☕', topic: 'cà phê hay trà', hint: 'Tranh luận vui cà phê vs trà, hỏi quán ruột, mô tả đồ uống yêu thích.' },
  { emoji: '💼', topic: 'công việc & một ngày điển hình', hint: 'Hỏi công việc/ngành học, một ngày điển hình, điều thích nhất trong việc đang làm.' },
  { emoji: '🎮', topic: 'game & giải trí', hint: 'Hỏi có chơi game không, game/ứng dụng đang nghiện, thời gian màn hình.' },
  { emoji: '🌟', topic: 'ước mơ & mục tiêu năm nay', hint: 'Hỏi mục tiêu năm nay, ước mơ lớn nhất, động viên nhau.' },
  { emoji: '👨‍🍳', topic: 'nấu ăn', hint: 'Hỏi họ có hay nấu ăn không, món tủ, thảm hoạ bếp núc từng gặp.' },
  { emoji: '🛍️', topic: 'mua sắm & món đồ mới', hint: 'Hỏi món đồ mua gần đây, thích mua online hay tại cửa hàng.' },
  { emoji: '🌙', topic: 'thói quen buổi sáng & buổi tối', hint: 'Hỏi họ là cú đêm hay chim sớm, thói quen trước khi ngủ/dậy sớm.' },
  { emoji: '📱', topic: 'mạng xã hội & điện thoại', hint: 'Hỏi app dùng nhiều nhất, chuyện vui trên mạng gần đây.' },
  { emoji: '🎉', topic: 'ngày lễ & kỷ niệm đáng nhớ', hint: 'Hỏi ngày lễ yêu thích, kỷ niệm vui nhất từng có.' },
]

const RANDOM_CHARACTERS: Record<string, string[]> = {
  ko: ['하은', '지호', '유나', '도윤', '서아'],
  en: ['Emma', 'Jack', 'Mia', 'Noah', 'Lily'],
  ja: ['さくら', 'ハルト', 'ユイ', 'レン'],
  zh: ['小美', '阿伟', '婷婷', '大龙'],
  de: ['Lena', 'Max', 'Sofia', 'Jonas'],
  vi: ['Lan', 'Minh', 'Thảo', 'Huy'],
}

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)]
}

/** Sinh một tình huống trò chuyện tự do với đề tài ngẫu nhiên — mỗi lần gọi một kiểu. */
export function randomScenario(lang: string): Scenario {
  const t = pick(RANDOM_TOPICS)
  const name = pick(RANDOM_CHARACTERS[lang] || RANDOM_CHARACTERS.en)
  return {
    id: 'random-' + Date.now(),
    title: `Tán gẫu: ${t.topic}`,
    emoji: t.emoji,
    character: name,
    role: `Tán gẫu: ${t.topic}`,
    avatar: '🎲',
    tags: ['talk'],
    situation: `Hai người bạn tán gẫu tự nhiên về ${t.topic}.`,
    persona: `Bạn là ${name}, một người bạn bản xứ vui tính đang tán gẫu với người học. Đề tài hôm nay: ${t.topic}. ${t.hint} Nói câu ngắn, tự nhiên như bạn bè, thỉnh thoảng hỏi ngược lại để người học nói nhiều hơn.`,
  }
}
