data/
media/

dictionaries/*
!dictionaries/KO-VI.KRDICT.zip

frontend/public/wordimg/
khungavatar/
nenkhungbangxephang/
TailieuToeic/

frontend/*
!frontend/dist
frontend/dist/**/*.map

dist/
node_modules/
**/node_modules/

config.toml
.env
.env.*
!.env.example

.git/
.venv/
**/__pycache__/
**/*.pyc
docs/
scripts/
tools/
cf/node_modules/
cf/dist/
*.bat
*.md
