export type AppView =
  | 'home'
  | 'learn'
  | 'library'
  | 'myvideos'
  | 'courses'
  | 'path'
  | 'speaking'
  | 'tutor'
  | 'english'
  | 'toeic'
  | 'korean'
  | 'topik'
  | 'chinese'
  | 'vocab'
  | 'flashcards'
  | 'activities'
  | 'leaderboard'
  | 'quests'
  | 'shop'
  | 'garden'
  | 'lingo'
  | 'dashboard'
  | 'pricing'
  | 'help'
  | 'about'
  | 'contact'
  | 'blog'
  | 'terms'
  | 'privacy'
  | 'notfound'
  | 'admin'

export type LearnTab = 'shadowing' | 'phatam' | 'chepchinhta' | 'dienkhuyet' | 'luyendich' | 'tomtat' | 'dubbing'

export type ThemeMode = 'light' | 'dark'

export type TopikLevel = 'Toàn bộ' | 'TOPIK1' | 'TOPIK2' | 'TOPIK3' | 'TOPIK4' | 'TOPIK5' | 'TOPIK6'
